# Generated by Django 2.2 on 2021-09-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'verbose_name_plural': 'Unidades de Medida'},
        ),
    ]
