# Generated by Django 2.2 on 2021-10-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0003_auto_20211004_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='registro',
            field=models.IntegerField(default=0),
        ),
    ]
