# Generated by Django 2.2 on 2021-10-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0005_remove_facturaenc_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadet',
            name='registro',
            field=models.IntegerField(default=0),
        ),
    ]
