# Generated by Django 2.2 on 2021-10-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0006_facturadet_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='registro',
            field=models.IntegerField(default=0),
        ),
    ]
