# Generated by Django 2.2 on 2021-10-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0007_facturaenc_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadet',
            name='registro',
            field=models.CharField(help_text='Digitos De RTN', max_length=100),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='registro',
            field=models.CharField(help_text='Digitos De RTN', max_length=100),
        ),
    ]
