# Generated by Django 2.2 on 2021-10-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0008_auto_20211017_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaenc',
            name='registro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
