# Generated by Django 2.2 on 2021-10-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0010_auto_20211017_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadet',
            name='registro',
            field=models.CharField(blank=True, default='000000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='registro',
            field=models.CharField(blank=True, default='000000', max_length=100, null=True),
        ),
    ]
