# Generated by Django 2.2 on 2021-10-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0011_auto_20211017_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadet',
            name='registro',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facturaenc',
            name='registro',
            field=models.IntegerField(default=0),
        ),
    ]
