# Generated by Django 2.2 on 2021-10-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasenc',
            options={'verbose_name': 'Encabezado Compra', 'verbose_name_plural': 'Encabezado Compras'},
        ),
    ]
